#!/bin/bash

#PBS -j oe
#PBS -o /lfs/h2/emc/ptmp/yali.mao/working_wafs/log.wafs_grib
#PBS -N wafs_octant
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -l debug=true
#PBS -q debug
#PBS -A GFS-DEV
##PBS -V

# cd $PBS_O_WORKDIR

# 8 means octants

set -x

############################################
# Set up the HOME directory
############################################
export NWROOT=/lfs/h2/emc/vpppg/noscrub/yali.mao/git
export HOMEwafs=${HOMEwafs:-${NWROOT}/WAFS.fork}

############################################
# Loading module
############################################
source $HOMEwafs/versions/run.ver
module reset
source $HOMEwafs/dev/modulefiles/wafs.sh
module list

############################################
# Modify ROOT after loading modules
############################################
export DBNROOT=${UTILROOT}/fakedbn

############################################
# Define envir
############################################
### envir: prod/dev/para/bkup/ges/test bkup2/ges2/para2/prod2/prd_p6
export envir=prod

############################################run
# set NET RUN
############################################
### NET: gfs/para/parallel-test/nam/rap/ dump/ens/nawips/nesdis/
export NET=wafs
export RUN=wafs

############################################
# user defined
############################################
export cyc=${cyc:-00}
export fhr=006
export PDY=$(cut -c 7-14 $COMROOT/date/t${cyc}z)

# wafs for octants (8 WAFS files)
export job=wafs_grib_${cyc}

export pid=${pid:-$$}
export jobid=${job}.${pid}

USER=$(whoami)

############################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ECF
# SENDDBN=YES--Alert output file to TOC
# KEEPDATA=NO--Remove temporary working
############################################
export SENDCOM=YES
export SENDDBN=YES
export SENDDBN_NTC=YES
export KEEPDATA=YES
 
############################################
# Define DATA, COMOUT and COMIN
############################################

export COMROOT=/lfs/h2/emc/ptmp/$USER/wafs_dwn/$envir/com

export COMPATH=${COMPATHgfs:-/lfs/h1/ops/prod/com/gfs}

export DATA=/lfs/h2/emc/ptmp/$USER/working_wafs/grib.$jobid

#############################################
# run the job
#############################################
sh $HOMEwafs/jobs/JWAFS_GRIB

exit
