#!/bin/bash

#PBS -j oe
#PBS -o /lfs/h2/emc/ptmp/yali.mao/working_wafs/log.wafs_grib2_0p25_blending
#PBS -N wafs_blending_0p25
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=27:mem=50GB
#PBS -q debug
#PBS -l debug=true
#PBS -A GFS-DEV
##PBS -V
##PBS -W umask=022

#cd $PBS_O_WORKDIR

set -x

############################################
# Set up the HOME directory
############################################
export NWROOT=/lfs/h2/emc/vpppg/noscrub/yali.mao/git
export HOMEwafs=${HOMEwafs:-${NWROOT}/WAFS.fork}

############################################
# Loading module
############################################
source $HOMEwafs/versions/run.ver
module reset
source $HOMEwafs/dev/modulefiles/wafs.sh

# make_NTC_file.pl
module load util_shared/$util_shared_ver

module list

############################################
# Modify ROOT after loading modules
############################################
export DBNROOT=${UTILROOT}/fakedbn
# for UK (canned)  data
export DCOMROOT=/lfs/h1/ops/prod/dcom
export DCOMROOT=/lfs/h1/ops/dev/dcom/test

############################################
# Define envir
############################################
### envir: prod/dev/para/bkup/ges/test bkup2/ges2/para2/prod2/prd_p6
export envir=prod

############################################
# set NET RUN
############################################
### NET: gfs/para/parallel-test/nam/rap/ dump/ens/nawips/nesdis/
export NET=wafs
export RUN=wafs

############################################
# user defined
############################################
export cyc=${cyc:-00}
export PDY=$(cut -c 7-14 $COMROOT/date/t${cyc}z)

# wafs_blending for blending icing turbulence of US and UK
export job=wafs_blending_0p25_${cyc}

export pid=${pid:-$$}
export jobid=${job}.${pid}

USER=$(whoami)

############################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ECF
# SENDDBN=YES--Alert output file to TOC
# KEEPDATA=NO--Remove temporary working
############################################
export SENDCOM=YES
export SENDDBN=YES
export SENDDBN_NTC=YES
export KEEPDATA=YES
 
############################################
# Define DATA PCOM, COMOUT and COMIN
############################################
# For COMOUT
export COMROOT=/lfs/h2/emc/ptmp/$USER/wafs_dwn/$envir/com

# For COMIN
# export COMPATH=$COMROOT/wafs
export COMPATH=/lfs/h2/emc/ptmp/yali.mao/wafsx001/prod/com/wafs

export DATA=/lfs/h2/emc/ptmp/$USER/working_wafs.$jobid

############################################
# run the job
#############################################
# Set up mailing list
if [[ "${envir}" != "prod" ]]; then
    MAILTO="nco.spa@noaa.gov"
fi
export MAILTO=${MAILTO:-"nco.spa@noaa.gov,ncep.sos@noaa.gov,nco.sos@noaa.gov,nco.hpc.dataflow@noaa.gov"}

sh $HOMEwafs/jobs/JWAFS_GRIB2_0P25_BLENDING

exit
