#!/bin/bash

########################################
# WAFS UPP PRODUCT GENERATION
########################################

date
export PS4='$SECONDS + '
set -x

####################################
# make temp directory
####################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p "${DATA}" && cd "${DATA}"

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=${cycle:-"t${cyc}z"}
setpdy.sh
. ./PDY

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
####################################
export SENDCOM=${SENDCOM:-"YES"}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-wafs}
export RUN=${RUN:-gefs}

##############################################
# Define COM directories
##############################################
export COMINgefs=${COMINgefs:-$(compath.py "${envir}/gefs/${gefs_ver}")"/gefs.${PDY}/${cyc}/atmos/sfcsig"}
export COMOUT=${COMOUT:-$(compath.py -o "${NET}/${wafs_ver}")"/${RUN}.${PDY}/${cyc}"}
mkdir -p "${COMOUT}"

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
####################################
export USHwafs=${USHwafs:-$HOMEwafs/ush}
export EXECwafs=${EXECwafs:-$HOMEwafs/exec}
export PARMwafs=${PARMwafs:-$HOMEwafs/parm}
export FIXwafs=${FIXwafs:-$HOMEwafs/fix}

#########################################################
# print current environment
#########################################################
env

#########################################################
# Execute the Script
#########################################################
# Run UPP with 1 thread
export OMP_NUM_THREADS=1

ntasks=$(cat $PBS_NODEFILE | wc -l)
export MPIRUN=${MPIRUN:-"mpiexec -l -n $ntasks -ppn $ntasks --cpu-bind depth --depth 1"}

"${HOMEwafs}/scripts/exwafs_gefs_upp.sh"
export err=$?
err_chk

if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi

##############################
# Remove the Temporary working directory
##############################
if [[ "${KEEPDATA^^}" != "YES" ]]; then
  rm -rf "${DATA}"
fi

date
