#!/bin/sh

########################################
# WAFS GRIB2 AWIPS PRODUCT GENERATION
########################################

date
export PS4='$SECONDS + ' 
set -x

# keep the working directory or not
export KEEPDATA=${KEEPDATA:-NO}

############################################
# Specify it is production or developmen
############################################
export envir=${envir:-prod}
# print current environment
env

############################################
# Working Directory
############################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

############################################
# Output for executables
############################################
export pgmout=OUTPUT.$$

############################################
# Load the UTILITIES module
############################################
#### module load prod_util
#### module load grib_util

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=t${cyc}z 
setpdy.sh
. ./PDY

############################################
# Set up the NET and RUN
############################################
export NET=${NET:-wafs}
export RUN=${RUN:-wafs}

############################################
# Specify HOME Directory 
############################################
export HOMEwafs=${HOMEwafs:-${NWROOT}/wafs.${wafs_ver}}
export EXECwafs=$HOMEwafs/exec
export FIXwafs=$HOMEwafs/fix/wafs
export PARMwafs=$HOMEwafs/parm/wafs
export USHwafs=$HOMEwafs/ush
export SCRIPTSwafs=$HOMEwafs/scripts

################################################
# Set up the input/output directory
################################################

export COMIN=${COMIN:-$(compath.py $envir/$NET/$wafs_ver)/$RUN.$PDY/$cyc}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$wafs_ver)/$RUN.$PDY/$cyc}
export PCOM=${PCOM:-$COMOUT/wmo}

export COMINgfs=${COMINgfs:-$(compath.py $envir/gfs/$gfs_ver)/gfs.$PDY/$cyc/atmos}

if [ $SENDCOM = YES ] ; then
  mkdir -p $COMOUT $PCOM
fi

##############################################
# Set up the forecast hours
##############################################
export FHOURS=${FHOURS:-"00 06 09 12 15 18 21 24 27 30 33 36 42 48 54 60 66 72"}

############################################
# Execute the script.
############################################

NP=`echo $FHOURS | wc -w`
export MPIRUN=${MPIRUN:-"mpiexec -np $NP -cpu-bind verbose,core cfp"}

rm wafsgrib2.cmdfile
ic=0
for fcsthrs in $FHOURS ; do
  if [ `echo $MPIRUN | cut -d " " -f1` = 'srun' ] ; then
    echo $ic ${SCRIPTSwafs}/exwafs_grib2.sh $fcsthrs >> wafsgrib2.cmdfile
  else
    echo ${SCRIPTSwafs}/exwafs_grib2.sh $fcsthrs >> wafsgrib2.cmdfile
    export MP_PGMMODEL=mpmd
  fi
  ic=`expr $ic + 1`
done

$MPIRUN wafsgrib2.cmdfile

export err=$?; err_chk

echo "JOB $job HAS COMPLETED NORMALLY!"

############################################
# print exec output
############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

############################################
# remove temporary working directory
############################################
if [ $KEEPDATA != YES ] ; then
    rm -rf $DATA
fi

date

