#!/bin/bash

########################################
# WAFS UPP PRODUCT GENERATION
########################################

export PS4='$SECONDS + '
date
set -x

# keep the working directory or not
export KEEPDATA=${KEEPDATA:-NO}

####################################
# Specify whether the run is production or development
####################################
export envir=${envir:-prod}
# print current environment
env

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-wafs}
export RUN=${RUN:-wafs}

export RUNupp=${RUNupp:-gfs}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=t${cyc}z
setpdy.sh
. ./PDY


####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEwafs=${HOMEwafs:-${NWROOT}/wafs.${wafs_ver}}
export EXECwafs=$HOMEwafs/exec
export FIXwafs=$HOMEwafs/fix/upp
export PARMwafs=$HOMEwafs/parm/upp
export USHwafs=$HOMEwafs/ush
export SCRIPTSwafs=$HOMEwafs/scripts

export POSTGPEXEC=${POSTGPEXEC:-$EXECwafs/ncep_post}
export POSTGRB2TBL=${POSTGRB2TBL:-${g2tmpl_ROOT}/share/params_grib2_tbl_new}

##############################################
# Define COM directories
##############################################
export COMINgfs=${COMINgfs:-$(compath.py $envir/$RUNupp/$gfs_ver)/gfs.$PDY/$cyc/atmos}

export COMOUT=${COMOUT:-$(compath.py -o $NET/$wafs_ver)/$RUN.$PDY/$cyc/upp}
mkdir -p $COMOUT

####################################
# Specify Special Post Vars
####################################
numx=${numx:-1}

####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=900
export SLEEP_INT=5


#########################################################
# Execute the Script
#########################################################
export MPIRUN=${MPIRUN:-'mpiexec -l -n 126 -ppn 126 --cpu-bind depth --depth 1'}
$SCRIPTSwafs/exwafs_upp.sh

##############################
# Remove the Temporary working directory
##############################
if [ $KEEPDATA = NO ]; then
  rm -rf $DATA
fi

date
