#!/bin/sh

########################################
# WAFS GRIB  AWIPS PRODUCT GENERATION
########################################
date
export PS4='$SECONDS + ' 
set -xa

export KEEPDATA=${KEEPDATA:-NO}

############################################
# Specify it is production or developmen
############################################
export envir=${envir:-prod}
# print current environment
env

############################################
# Working Directory
############################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

############################################
# Output for executables
############################################
export pgmout=OUTPUT.$$

############################################
# Load the UTILITIES module
############################################
#### module load prod_util
#### module load grib_util

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=t${cyc}z 
setpdy.sh
. ./PDY

export RERUN=${RERUN:-NO}

############################################
# Set up the NET and RUN
############################################
export NET=${NET:-wafs}
export RUN=${RUN:-wafs}

############################################
# Specify HOME Directory
############################################
export HOMEwafs=${HOMEwafs:-${NWROOT}/wafs.${wafs_ver}}
export EXECwafs=$HOMEwafs/exec
export FIXwafs=$HOMEwafs/fix/wafs
export PARMwafs=$HOMEwafs/parm/wafs
export USHwafs=$HOMEwafs/ush
export SCRIPTSwafs=$HOMEwafs/scripts

################################################
# Set up the input/output directory
################################################
export COMOUT=${COMOUT:-$(compath.py -o $NET/$wafs_ver)/$RUN.$PDY/$cyc} 
export PCOM=${PCOM:-$COMOUT/wmo}

export COMINgfs=${COMINgfs:-$(compath.py ${envir}/gfs/${gfs_ver})/gfs.${PDY}/${cyc}/atmos}

if [ $SENDCOM = YES ] ; then
  mkdir -p $COMOUT $PCOM
fi

##############################################
# Set up the forecast hours
##############################################
export FHOURS=${FHOURS:-"06 12 18 24 30 36 42 48 54 60 66 72"}

############################################
# Execute the script.
############################################

ic=0
for fhr in $FHOURS ; do
    ${SCRIPTSwafs}/exwafs_grib.sh $fhr
done

export err=$?; err_chk

echo "JOB $job HAS COMPLETED NORMALLY!"

############################################
# print exec output
############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

############################################
# remove temporary working directory
############################################
if [ $KEEPDATA != YES ] ; then
    rm -rf $DATA
fi

date
